package uz.carapp.rentcarapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarBodyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarBodyAllPropertiesEquals(CarBody expected, CarBody actual) {
        assertCarBodyAutoGeneratedPropertiesEquals(expected, actual);
        assertCarBodyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarBodyAllUpdatablePropertiesEquals(CarBody expected, CarBody actual) {
        assertCarBodyUpdatableFieldsEquals(expected, actual);
        assertCarBodyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarBodyAutoGeneratedPropertiesEquals(CarBody expected, CarBody actual) {
        assertThat(actual)
            .as("Verify CarBody auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarBodyUpdatableFieldsEquals(CarBody expected, CarBody actual) {
        assertThat(actual)
            .as("Verify CarBody relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarBodyUpdatableRelationshipsEquals(CarBody expected, CarBody actual) {
        // empty method
    }
}
