package uz.carapp.rentcarapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarClassAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarClassAllPropertiesEquals(CarClass expected, CarClass actual) {
        assertCarClassAutoGeneratedPropertiesEquals(expected, actual);
        assertCarClassAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarClassAllUpdatablePropertiesEquals(CarClass expected, CarClass actual) {
        assertCarClassUpdatableFieldsEquals(expected, actual);
        assertCarClassUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarClassAutoGeneratedPropertiesEquals(CarClass expected, CarClass actual) {
        assertThat(expected)
            .as("Verify CarClass auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarClassUpdatableFieldsEquals(CarClass expected, CarClass actual) {
        assertThat(expected)
            .as("Verify CarClass relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarClassUpdatableRelationshipsEquals(CarClass expected, CarClass actual) {
        // empty method
    }
}
