package uz.carapp.rentcarapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateAllPropertiesEquals(CarTemplate expected, CarTemplate actual) {
        assertCarTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertCarTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateAllUpdatablePropertiesEquals(CarTemplate expected, CarTemplate actual) {
        assertCarTemplateUpdatableFieldsEquals(expected, actual);
        assertCarTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateAutoGeneratedPropertiesEquals(CarTemplate expected, CarTemplate actual) {
        assertThat(actual)
            .as("Verify CarTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateUpdatableFieldsEquals(CarTemplate expected, CarTemplate actual) {
        assertThat(actual)
            .as("Verify CarTemplate relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateUpdatableRelationshipsEquals(CarTemplate expected, CarTemplate actual) {
        assertThat(actual)
            .as("Verify CarTemplate relationships")
            .satisfies(a -> assertThat(a.getModel()).as("check model").isEqualTo(expected.getModel()));
    }
}
