package uz.carapp.rentcarapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarTemplateParamAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateParamAllPropertiesEquals(CarTemplateParam expected, CarTemplateParam actual) {
        assertCarTemplateParamAutoGeneratedPropertiesEquals(expected, actual);
        assertCarTemplateParamAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateParamAllUpdatablePropertiesEquals(CarTemplateParam expected, CarTemplateParam actual) {
        assertCarTemplateParamUpdatableFieldsEquals(expected, actual);
        assertCarTemplateParamUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateParamAutoGeneratedPropertiesEquals(CarTemplateParam expected, CarTemplateParam actual) {
        assertThat(actual)
            .as("Verify CarTemplateParam auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateParamUpdatableFieldsEquals(CarTemplateParam expected, CarTemplateParam actual) {
        assertThat(actual)
            .as("Verify CarTemplateParam relevant properties")
            .satisfies(a -> assertThat(a.getParamVal()).as("check paramVal").isEqualTo(expected.getParamVal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarTemplateParamUpdatableRelationshipsEquals(CarTemplateParam expected, CarTemplateParam actual) {
        assertThat(actual)
            .as("Verify CarTemplateParam relationships")
            .satisfies(a -> assertThat(a.getCarTemplate()).as("check carTemplate").isEqualTo(expected.getCarTemplate()))
            .satisfies(a -> assertThat(a.getParam()).as("check param").isEqualTo(expected.getParam()))
            .satisfies(a -> assertThat(a.getParamValue()).as("check paramValue").isEqualTo(expected.getParamValue()));
    }
}
