package uz.carapp.rentcarapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocAttachmentAllPropertiesEquals(DocAttachment expected, DocAttachment actual) {
        assertDocAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertDocAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocAttachmentAllUpdatablePropertiesEquals(DocAttachment expected, DocAttachment actual) {
        assertDocAttachmentUpdatableFieldsEquals(expected, actual);
        assertDocAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocAttachmentAutoGeneratedPropertiesEquals(DocAttachment expected, DocAttachment actual) {
        assertThat(actual)
            .as("Verify DocAttachment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocAttachmentUpdatableFieldsEquals(DocAttachment expected, DocAttachment actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocAttachmentUpdatableRelationshipsEquals(DocAttachment expected, DocAttachment actual) {
        assertThat(actual)
            .as("Verify DocAttachment relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()))
            .satisfies(a -> assertThat(a.getAttachment()).as("check attachment").isEqualTo(expected.getAttachment()));
    }
}
