package uz.carapp.rentcarapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModelAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelAttachmentAllPropertiesEquals(ModelAttachment expected, ModelAttachment actual) {
        assertModelAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertModelAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelAttachmentAllUpdatablePropertiesEquals(ModelAttachment expected, ModelAttachment actual) {
        assertModelAttachmentUpdatableFieldsEquals(expected, actual);
        assertModelAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelAttachmentAutoGeneratedPropertiesEquals(ModelAttachment expected, ModelAttachment actual) {
        assertThat(actual)
            .as("Verify ModelAttachment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelAttachmentUpdatableFieldsEquals(ModelAttachment expected, ModelAttachment actual) {
        assertThat(actual)
            .as("Verify ModelAttachment relevant properties")
            .satisfies(a -> assertThat(a.getIsMain()).as("check isMain").isEqualTo(expected.getIsMain()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModelAttachmentUpdatableRelationshipsEquals(ModelAttachment expected, ModelAttachment actual) {
        assertThat(actual)
            .as("Verify ModelAttachment relationships")
            .satisfies(a -> assertThat(a.getModel()).as("check model").isEqualTo(expected.getModel()))
            .satisfies(a -> assertThat(a.getAttachment()).as("check attachment").isEqualTo(expected.getAttachment()));
    }
}
