package uz.carapp.rentcarapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParametrAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrAllPropertiesEquals(Parametr expected, Parametr actual) {
        assertParametrAutoGeneratedPropertiesEquals(expected, actual);
        assertParametrAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrAllUpdatablePropertiesEquals(Parametr expected, Parametr actual) {
        assertParametrUpdatableFieldsEquals(expected, actual);
        assertParametrUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrAutoGeneratedPropertiesEquals(Parametr expected, Parametr actual) {
        assertThat(expected)
            .as("Verify Parametr auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrUpdatableFieldsEquals(Parametr expected, Parametr actual) {
        assertThat(expected)
            .as("Verify Parametr relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrUpdatableRelationshipsEquals(Parametr expected, Parametr actual) {
        // empty method
    }
}
